[
    {
        "data": {
            "model_name": "whisper_medium"
        },
        "error": "InferenceException",
        "message": "InferenceException(model_name=whisper_medium)",
        "stacktrace": "\u001b[36mray::ServeReplica:asr_deployment:WhisperDeployment.handle_request_with_rejection()\u001b[39m (pid=180349, ip=172.17.0.10, actor_id=eeae86b514d84eac47580a8801000000, repr=<ray.serve._private.replica.ServeReplica:asr_deployment:WhisperDeployment object at 0x7f94502a9f30>)\n    async for result in self._call_user_generator(\n  File \"/root/.cache/pypoetry/virtualenvs/aana-XDlPP_xZ-py3.10/lib/python3.10/site-packages/ray/serve/_private/replica.py\", line 460, in _call_user_generator\n    raise e from None\n  File \"/root/.cache/pypoetry/virtualenvs/aana-XDlPP_xZ-py3.10/lib/python3.10/site-packages/ray/serve/_private/replica.py\", line 1150, in call_user_method\n    raise e from None\nray.exceptions.RayTaskError: \u001b[36mray::ServeReplica:asr_deployment:WhisperDeployment.handle_request_with_rejection()\u001b[39m (pid=180349, ip=172.17.0.10)\n  File \"/root/.cache/pypoetry/virtualenvs/aana-XDlPP_xZ-py3.10/lib/python3.10/site-packages/ray/serve/_private/utils.py\", line 168, in wrap_to_ray_error\n    raise exception\n  File \"/root/.cache/pypoetry/virtualenvs/aana-XDlPP_xZ-py3.10/lib/python3.10/site-packages/ray/serve/_private/replica.py\", line 1131, in call_user_method\n    result = await self._handle_user_method_result(\n  File \"/root/.cache/pypoetry/virtualenvs/aana-XDlPP_xZ-py3.10/lib/python3.10/site-packages/ray/serve/_private/replica.py\", line 1038, in _handle_user_method_result\n    async for r in result:\n  File \"/root/aana_sdk/aana/deployments/base_deployment.py\", line 144, in wrapper_generator\n    raise cache[\"exception\"]\naana.exceptions.runtime.InferenceException: InferenceException(model_name=whisper_medium)"
    }
]